### ISSUE TITLE
Add support to supervise objects that require parameters in constructor

### ISSUE THREAD

**Issue by javydreamercsw** [jhalterman/sarge#11]
Right now it only seems to work with classes with empty constructor. This is not always the case specially when working with third party libraries.

**Comment by jhalterman** [comment]
I'd be happy to look at a PR for this.

**Comment by javydreamercsw** [comment]
Looks like the Hudson failures are unrelated to the code but needs someone to take a look.

**Comment by jhalterman** [comment]
Included in 0.3.2.
