### ISSUE TITLE
Sarge not picking up the exception second time

### ISSUE THREAD

**Issue by sks** [jhalterman/sarge#6]
Hi,

Not sure if we are missing something here, but Sarge did not pick up the exception the second time Exception was thrown from the object.

Sample gist (modified from BackOffTest.java)
https://gist.github.com/sks/28f1b8bc8db6f044dc93

Please let us know in case we are missing something here.

--Thanks
Sabith

**Comment by dfdemar** [comment]
If I'm understanding Sarge correctly, it looks like you used up all your retries in the first try-catch block. When it gets to the second try-catch there are no retries left so `foo.doSomething()` gets called and fails and Sarge will not retry it.

Your retry window is set to infinity so the retry count will never get reset.

**Comment by jhalterman** [comment]
I think this is actually an issue where retries are not being tracked separately for each invocation and are instead being cached (for some reason.... wish I could recall why). This doesn't seem appropriate though. Fix incoming.

**Comment by sks** [comment]
I've since gone and started using https://github.com/spring-projects/spring-retry

**Comment by jhalterman** [comment]
@sks No worries :) Another more recent thing worth checking out is [Failsafe](https://github.com/jhalterman/failsafe/), which we use for the more concise (than spring-retry) syntax, as well as async retries and other things.

**Comment by dfdemar** [comment]
@jhalterman How does Failsafe compare to Sarge?

**Comment by jhalterman** [comment]
@dfdemar Failsafe is a bit more simple conceptually - it just executes individual code blocks (Runnables/Callables) according to some configuration, such as a `RetryPolicy` or `CircuitBreaker`.

Sarge also handles failures via retries, but they're handled transparently for any method that's invoked against a supervised object. The idea is, for objects (such as services) where many methods may fail, Sarge allows you to apply a single policy towards handling those failures. Think of it like an object-wide try-catch. It also allows chaining of objects into supervision hierarchies which can map really well to the dependencies between services (one service depends on another, etc), even if the services don't necessarily call each other directly.

Overall, I'd say Sarge is a bit more niche in the types of problems you might want to use it for. Failsafe is more straightforward and can be used for pretty much anything. Failsafe also offers a few more features such as better retry policy config, async retries, and integration with async APIs.

**Comment by dfdemar** [comment]
Thanks for the info!
